### ISSUE TITLE
"zrem" discrepancy

### ISSUE THREAD

**Issue by rbgrouleff** [brigade/mock_redis#119]
Hi,

I've run into a small discrepancy between how MockRedis and Redis function.

When calling Redis::Client#zrem with an empty `Array` as the second argument, the method raises a `Redis::CommandError`. MockRedis#zrem doesn't raise this error.

### redis

```ruby
irb(main):003:0> redis.zrem('foo', [])
Redis::CommandError: ERR wrong number of arguments for 'zrem' command
	from /Users/rasmus/.gem/ruby/2.3.1/gems/redis-3.3.1/lib/redis/client.rb:121:in `call'
	from /Users/rasmus/.gem/ruby/2.3.1/gems/redis-3.3.1/lib/redis.rb:1571:in `block in zrem'
	from /Users/rasmus/.gem/ruby/2.3.1/gems/redis-3.3.1/lib/redis.rb:58:in `block in synchronize'
	from /Users/rasmus/.rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/rasmus/.gem/ruby/2.3.1/gems/redis-3.3.1/lib/redis.rb:58:in `synchronize'
	from /Users/rasmus/.gem/ruby/2.3.1/gems/redis-3.3.1/lib/redis.rb:1570:in `zrem'
	from (irb):3
	from /Users/rasmus/.rubies/ruby-2.3.1/bin/irb:11:in `<main>'
irb(main):004:0>
```

### redis-mock

```ruby
irb(main):003:0> mock_redis.zrem('foo', [])
=> 0
irb(main):004:0>
```

**Comment by sds** [comment]
Fixed in #120. Thanks!
